- name: Deploy ROSA HCP cluster
  hosts: localhost
  any_errors_fatal: true
  tasks:
  - name: Prepare ansible runner host
    include_tasks: tasks/prepare_ansible_runner.yml
    when: not skip_ansible_runner | bool
  - name: Login OCP
    include_tasks: tasks/login_ocp.yml
  - name: Check if local-cluster enabled
    shell: |
      oc get managedclusters -l local-cluster=true -ojson | jq -r '.items[].metadata.name'
    register: local_cluster
    ignore_errors: true
  - name: Check if there are any hosted clusters
    shell: |
      oc get hostedclusters -A -o name
    register: hosted_clusters

  - name: Deploy ROSA HCP
    import_role:
      name: deploy-rosa-hcp
