- name: Create rosa-creds-secret
  vars:
    global_secret: "{{'rosa-creds-secret'}}"
    ocm_client_id: "{{'ocm-client-id'}}"
    ocm_client_secret: "{{'ocm-client-secret'}}"
    ocm_client_api_url: "{{'ocm-client-api-url'}}"
  shell: "sleep 1"
#    shell: |
#      oc -n capa-system create secret generic {{ global_secret }} --from-literal=ocmClientID='ocm_client_id' --from-literal=ocmClientSecret='ocm_client_secret' --from-literal=ocmApiUrl='ocm_client_api_url'

