- name: Check if rosa-creds-secret already exists.
  shell: |
    # oc get secret -n capa-system rosa-creds-secret -ojsonpath='{.spec.defaultCertificate.name}'
  register: check_secret_exists
  changed_when: true

- name: Create rosa-creds-secret
  vars:
    global_secret: "{{'rosa-creds-secret'}}"
  shell: |
   #oc create secret generic -n ns-rosa-hcp rosa-creds-secret
   oc get secret -n ns-rosa-hcp rosa-creds-secret

